# Generated by Django 5.1.4 on 2024-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_id', models.IntegerField(max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
