# Generated by Django 5.1.4 on 2024-12-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_search', '0002_artistdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdetails',
            name='artist_id',
            field=models.IntegerField(),
        ),
    ]
