# Generated by Django 5.1.4 on 2024-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_alter_artistdetails_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleauth',
            name='auth',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='artist_name',
            field=models.CharField(max_length=2000),
        ),
    ]
