import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import NavBar from "./NavBar";
import { ReduxProvider } from "./ReduxProvider";
import { ThemeProvider } from "./ThemeContext";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider> {/* Keep your ThemeProvider here if it wraps the whole app */}
            <div className="d-flex flex-column min-vh-100">
              <NavBar />
              <main className="container flex-grow-1">
                {children} {/* This is where your page content will be rendered */}
              </main>
              <Footer />
            </div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
