import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import NavBar from "./NavBar";
import { ReduxProvider } from "./ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
